/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargePedestalAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargePedestalAddonDeed();
			}
		}

		[ Constructable ]
		public LargePedestalAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 0, 0, 0 );

		}

		public LargePedestalAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargePedestalAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargePedestalAddon();
			}
		}

		[Constructable]
		public LargePedestalAddonDeed()
		{
			Name = "LargePedestal";
		}

		public LargePedestalAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}