/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SandstoneOvenEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SandstoneOvenEastAddonDeed();
			}
		}

		[ Constructable ]
		public SandstoneOvenEastAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1121 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1122 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 0 );

		}

		public SandstoneOvenEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SandstoneOvenEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SandstoneOvenEastAddon();
			}
		}

		[Constructable]
		public SandstoneOvenEastAddonDeed()
		{
			Name = "SandstoneOvenEast";
		}

		public SandstoneOvenEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}