/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SandstoneOvenSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SandstoneOvenSouthAddonDeed();
			}
		}

		[ Constructable ]
		public SandstoneOvenSouthAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1135 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1134 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 0 );

		}

		public SandstoneOvenSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SandstoneOvenSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SandstoneOvenSouthAddon();
			}
		}

		[Constructable]
		public SandstoneOvenSouthAddonDeed()
		{
			Name = "SandstoneOvenSouth";
		}

		public SandstoneOvenSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}