/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ThinBrickChimneySouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ThinBrickChimneySouthAddonDeed();
			}
		}

		[ Constructable ]
		public ThinBrickChimneySouthAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2258 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2257 );
			AddComponent( ac, 0, 0, 0 );

		}

		public ThinBrickChimneySouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ThinBrickChimneySouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ThinBrickChimneySouthAddon();
			}
		}

		[Constructable]
		public ThinBrickChimneySouthAddonDeed()
		{
			Name = "ThinBrickChimneySouth";
		}

		public ThinBrickChimneySouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}