/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ThinBrickChimneyEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ThinBrickChimneyEastAddonDeed();
			}
		}

		[ Constructable ]
		public ThinBrickChimneyEastAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2261 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2262 );
			AddComponent( ac, 0, 0, 0 );

		}

		public ThinBrickChimneyEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ThinBrickChimneyEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ThinBrickChimneyEastAddon();
			}
		}

		[Constructable]
		public ThinBrickChimneyEastAddonDeed()
		{
			Name = "ThinBrickChimneyEast";
		}

		public ThinBrickChimneyEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}