/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class YewTreeAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new YewTreeAddonDeed();
			}
		}

		[Constructable]
		public YewTreeAddon()
		{
			AddComponent( new AddonComponent( 4803 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 4794 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 4802 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 4793 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 4801 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 4792 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 4806 ), 4, -3, 0 );
			AddComponent( new AddonComponent( 4797 ), 4, -3, 0 );
			AddComponent( new AddonComponent( 4805 ), 3, -2, 0 );
			AddComponent( new AddonComponent( 4796 ), 3, -2, 0 );
			AddComponent( new AddonComponent( 4807 ), 5, -4, 0 );
			AddComponent( new AddonComponent( 4798 ), -4, 5, 0 );
			AddComponent( new AddonComponent( 4799 ), -3, 4, 0 );
			AddComponent( new AddonComponent( 4790 ), -3, 4, 0 );
			AddComponent( new AddonComponent( 4800 ), -2, 3, 0 );
			AddComponent( new AddonComponent( 4791 ), -2, 3, 0 );
			AddComponent( new AddonComponent( 4804 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 4795 ), 2, -1, 0 );
		}

		public YewTreeAddon( Serial serial )
			: base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class YewTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new YewTreeAddon();
			}
		}

		[Constructable]
		public YewTreeAddonDeed()
		{
			Name = "YewTree";
		}

		public YewTreeAddonDeed( Serial serial )
			: base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
